<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <style>
            *{
                margin: 0;
                padding: 0;
            }
            .rate {
                float: left;
                height: 46px;
                padding: 0 10px;
            }
            .rate:not(:checked) > input {
                position:absolute;
                top:-9999px;
            }
            .rate:not(:checked) > label {
                float:right;
                width:1em;
                overflow:hidden;
                white-space:nowrap;
                cursor:pointer;
                font-size:30px;
                color:#ccc;
            }
            .rate:not(:checked) > label:before {
                content: '★ ';
            }
            .rate > input:checked ~ label {
                color: #ffc700;    
            }
            .rate:not(:checked) > label:hover,
            .rate:not(:checked) > label:hover ~ label {
                color: #deb217;  
            }
            .rate > input:checked + label:hover,
            .rate > input:checked + label:hover ~ label,
            .rate > input:checked ~ label:hover,
            .rate > input:checked ~ label:hover ~ label,
            .rate > label:hover ~ input:checked ~ label {
                color: #c59b08;
            }
        </style>
    </head>
    <body>
        <div class="m-2 p-4 w-50">
            <div class="card" id="comentarios">
                <div class="card-body">
                    <small class="text-muted">No hay reseñas</small>
                </div>
            </div>
            <br>
            <form action="server:port/create_comment/<?php echo $url ?> method="POST">
                <div class="form-group">
                    
                    <textarea class="form-control" name="comment" rows="3" placeholder="Escribe tu comentario..."></textarea>
                    <div class="rate">
                        <input type="radio" id="star5" name="score" value="5" />
                        <label for="star5" title="text">5 stars</label>
                        <input type="radio" id="star4" name="score" value="4" />
                        <label for="star4" title="text">4 stars</label>
                        <input type="radio" id="star3" name="score" value="3" />
                        <label for="star3" title="text">3 stars</label>
                        <input type="radio" id="star2" name="score" value="2" />
                        <label for="star2" title="text">2 stars</label>
                        <input type="radio" id="star1" name="score" value="1" />
                        <label for="star1" title="text">1 star</label>
                      </div>
                    <button type="button" class="btn btn-primary float-right w-50 m-2">Post</button>
                </div>
            </form>
        </div>
    </body>
</html>