<div class="m-2 p-4 w-50">
    <div class="card" id="comentarios">
        <div class="card-body">
            <div class="text-center"><h1 class="p-2"><?php echo $score ?><span style="color: #deb217">★</span></h1></div>
            <hr>
            <div style="overflow-y:auto;max-height: 12rem;padding-right: 1rem;">
                <?php echo $content ?>
            </div>
        </div>
    </div>
    <br>
    <form action="crearComentario" method="POST">
        <div class="form-group">
            <input name="url" value="<?php echo $url ?>" hidden>
            <textarea class="form-control" name="comment" rows="3" placeholder="Escribe tu comentario..."></textarea>
            <div class="rate">
                <input type="radio" id="star5" name="score" value="5" />
                <label for="star5" title="text">5 stars</label>
                <input type="radio" id="star4" name="score" value="4" />
                <label for="star4" title="text">4 stars</label>
                <input type="radio" id="star3" name="score" value="3" />
                <label for="star3" title="text">3 stars</label>
                <input type="radio" id="star2" name="score" value="2" />
                <label for="star2" title="text">2 stars</label>
                <input type="radio" id="star1" name="score" value="1" />
                <label for="star1" title="text">1 star</label>
                </div>
            <button type="button" class="btn btn-primary float-right w-50 m-2">Post</button>
        </div>
    </form>
</div>